export const data = [
  {
    id: 1,
    name: "Lucas Films Private Limited",
    code: "LUCF",
    logo: "",
    domains: [
      "@lucasfilm.com",
      "@lucasstarwars.com",
      "@starwars.com",
      "@marvel.com",
      "@dccomics.com",
    ],
    reg_date: "April 2021",
    user: [
      {
        user_id: 1,
        user_name: "Salma Shaik",
        email: "salma.rivaan@gmail.com",
      },
      {
        user_id: 2,
        user_name: "Afsar",
        email: "afsarsk@gmail.com",
      },
      {
        user_id: 3,
        user_name: "Arwaan",
        email: "arwaanafsar@gmail.com",
      },
      {
        user_id: 4,
        user_name: "Nidhi",
        email: "nidhiayyar@gmail.com",
      },
      {
        user_id: 5,
        user_name: "Jitesh Nair",
        email: "Jiteshnair@gmail.com",
      },
      {
        user_id: 6,
        user_name: "Swati",
        email: "swatik@gmail.com",
      },
    ],
    entities: [
      {
        entity_id: 1,
        billing_location: "Riyadh,Kingdom of Saudi Arabia",
        entity_name: "Lucas Films Private Limited",
        entity_code: "LUCF01",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>LucasFilms MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 June 2025",
        duration_of_storage: "90 days",
        TAX_reg_number: "JHGJH89KU0873KHH",
        TRN_validity: "5 June 2025",
        currency: "US Dollar (S)",
        vat: "5%",
        wht: "5%",
        corporate_price_per_MSLA: [
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 2,
        billing_location: "Banglaore,India",
        entity_name: "Einfochip Private Limited",
        entity_code: "EINFO21",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>EINFO MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 March 2025",
        duration_of_storage: "60 days",
        TAX_reg_number: "KHGJH89KU0873KHH",
        TRN_validity: "5 June 2026",
        currency: "US Dollar (S)",
        vat: "6%",
        wht: "7%",
        corporate_price_per_MSLA: [
          {
            service: "Sanskrit Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.2,
            Offered_price: 0.19,
            discount: "10% ( 19% )",
          },
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 3,
        billing_location: "Tesla,United States Of America",
        entity_name: "Tesla Motors Private Limited",
        entity_code: "TSL01",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>Tesla MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "25 January 2023",
        duration_of_storage: "100 days",
        TAX_reg_number: "JHGJHKJDFH873K2H",
        TRN_validity: "5 June 2025",
        currency: "US Dollar (S)",
        vat: "5%",
        wht: "5%",
        corporate_price_per_MSLA: [
          {
            service: "Latin Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "8% ( 10% )",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "GREEN THUMB Private Limited",
    code: "GTC",
    logo: "",
    domains: ["@greenthumb.com", "@greentb.com", "@greentc.com"],
    reg_date: "July 2021",
    user: [
      {
        user_id: 1,
        user_name: "Salma Shaik",
        email: "salma.rivaan@gmail.com",
      },
      {
        user_id: 2,
        user_name: "Afsar",
        email: "afsarsk@gmail.com",
      },
      {
        user_id: 3,
        user_name: "Arwaan",
        email: "arwaanafsar@gmail.com",
      },
      {
        user_id: 4,
        user_name: "Nidhi",
        email: "nidhiayyar@gmail.com",
      },
      {
        user_id: 5,
        user_name: "Jitesh Nair",
        email: "Jiteshnair@gmail.com",
      },
    ],
    entities: [
      {
        entity_id: 1,
        billing_location: "Hyderabad,India",
        entity_name: "GREENTHUMB Private Limited",
        entity_code: "GT02",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>GT MOS_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 June 2025",
        duration_of_storage: "90 days",
        TAX_reg_number: "JHGJH89KU0873KHH",
        TRN_validity: "5 June 2025",
        currency: "IN Rupee (Rs)",
        vat: "5%",
        wht: "5%",
        corporate_price_per_MSLA: [
          {
            service: "Hindi Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 2,
        billing_location: "Banglaore,India",
        entity_name: "Einfochip Private Limited",
        entity_code: "EINFO21",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>EINFO MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 March 2025",
        duration_of_storage: "60 days",
        TAX_reg_number: "KHGJH89KU0873KHH",
        TRN_validity: "5 June 2026",
        currency: "US Dollar (S)",
        vat: "6%",
        wht: "7%",
        corporate_price_per_MSLA: [
          {
            service: "kannadam Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.2,
            Offered_price: 0.19,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 3,
        billing_location: "Banglaore,India",
        entity_name: "Einfochip Private Limited",
        entity_code: "EINFO21",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>EINFO MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 March 2025",
        duration_of_storage: "60 days",
        TAX_reg_number: "KHGJH89KU0873KHH",
        TRN_validity: "5 June 2026",
        currency: "US Dollar (S)",
        vat: "6%",
        wht: "7%",
        corporate_price_per_MSLA: [
          {
            service: "kannadam Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.2,
            Offered_price: 0.19,
            discount: "10% ( 19% )",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "EZ Works Private Limited",
    code: "EZW",
    logo: "",
    domains: [
      "@ezworks.com",
      "@ezworksstar.com",
      "@ezworkswars.com",
      "@ezworkscoders.com",
      "@ezworksmanage.com",
    ],
    reg_date: "september 2022",
    user: [
      {
        user_id: 1,
        user_name: "Salma Shaik",
        email: "salma.rivaan@gmail.com",
      },
      {
        user_id: 2,
        user_name: "Afsar",
        email: "afsarsk@gmail.com",
      },
      {
        user_id: 3,
        user_name: "Arwaan",
        email: "arwaanafsar@gmail.com",
      },
      {
        user_id: 4,
        user_name: "Nidhi",
        email: "nidhiayyar@gmail.com",
      },
      {
        user_id: 5,
        user_name: "Jitesh Nair",
        email: "Jiteshnair@gmail.com",
      },
      {
        user_id: 6,
        user_name: "Swati",
        email: "swatik@gmail.com",
      },
    ],
    entities: [
      {
        entity_id: 1,
        billing_location: "Bangalore of Karnataka",
        entity_name: "Lucas Films Private Limited",
        entity_code: "LUCF01",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>LucasFilms MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 June 2025",
        duration_of_storage: "90 days",
        TAX_reg_number: "JHGJH89KU0873KHH",
        TRN_validity: "5 June 2025",
        currency: "US Dollar (S)",
        vat: "5%",
        wht: "5%",
        corporate_price_per_MSLA: [
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 2,
        billing_location: "Banglaore,India",
        entity_name: "Einfochip Private Limited",
        entity_code: "EINFO21",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>EINFO MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 March 2025",
        duration_of_storage: "60 days",
        TAX_reg_number: "KHGJH89KU0873KHH",
        TRN_validity: "5 June 2026",
        currency: "US Dollar (S)",
        vat: "6%",
        wht: "7%",
        corporate_price_per_MSLA: [
          {
            service: "Website Development",
            EZ_assured: true,
            units: "Words",
            list_price: 0.2,
            Offered_price: 0.19,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 2,
        billing_location: "Banglaore,India",
        entity_name: "Einfochip Private Limited",
        entity_code: "EINFO21",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>EINFO MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 March 2025",
        duration_of_storage: "60 days",
        TAX_reg_number: "KHGJH89KU0873KHH",
        TRN_validity: "5 June 2026",
        currency: "US Dollar (S)",
        vat: "6%",
        wht: "7%",
        corporate_price_per_MSLA: [
          {
            service: "Website Development",
            EZ_assured: true,
            units: "Words",
            list_price: 0.2,
            Offered_price: 0.19,
            discount: "10% ( 19% )",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "EZ Works Private Limited",
    code: "EZW",
    logo: "",
    domains: [
      "@ezworks.com",
      "@ezworksstar.com",
      "@ezworkswars.com",
      "@ezworkscoders.com",
      "@ezworksmanage.com",
    ],
    reg_date: "september 2022",
    user: [
      {
        user_id: 1,
        user_name: "Salma Shaik",
        email: "salma.rivaan@gmail.com",
      },
      {
        user_id: 2,
        user_name: "Afsar",
        email: "afsarsk@gmail.com",
      },
      {
        user_id: 3,
        user_name: "Arwaan",
        email: "arwaanafsar@gmail.com",
      },
      {
        user_id: 4,
        user_name: "Nidhi",
        email: "nidhiayyar@gmail.com",
      },
      {
        user_id: 5,
        user_name: "Jitesh Nair",
        email: "Jiteshnair@gmail.com",
      },
      {
        user_id: 6,
        user_name: "Swati",
        email: "swatik@gmail.com",
      },
    ],
    entities: [
      {
        entity_id: 1,
        billing_location: "Bangalore of Karnataka",
        entity_name: "Lucas Films Private Limited",
        entity_code: "LUCF01",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>LucasFilms MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 June 2025",
        duration_of_storage: "90 days",
        TAX_reg_number: "JHGJH89KU0873KHH",
        TRN_validity: "5 June 2025",
        currency: "US Dollar (S)",
        vat: "5%",
        wht: "5%",
        corporate_price_per_MSLA: [
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 2,
        billing_location: "Banglaore,India",
        entity_name: "Einfochip Private Limited",
        entity_code: "EINFO21",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>EINFO MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 March 2025",
        duration_of_storage: "60 days",
        TAX_reg_number: "KHGJH89KU0873KHH",
        TRN_validity: "5 June 2026",
        currency: "US Dollar (S)",
        vat: "6%",
        wht: "7%",
        corporate_price_per_MSLA: [
          {
            service: "Website Development",
            EZ_assured: true,
            units: "Words",
            list_price: 0.2,
            Offered_price: 0.19,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 2,
        billing_location: "Banglaore,India",
        entity_name: "Einfochip Private Limited",
        entity_code: "EINFO21",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>EINFO MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 March 2025",
        duration_of_storage: "60 days",
        TAX_reg_number: "KHGJH89KU0873KHH",
        TRN_validity: "5 June 2026",
        currency: "US Dollar (S)",
        vat: "6%",
        wht: "7%",
        corporate_price_per_MSLA: [
          {
            service: "Website Development",
            EZ_assured: true,
            units: "Words",
            list_price: 0.2,
            Offered_price: 0.19,
            discount: "10% ( 19% )",
          },
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Mahindra Motors Private Limited",
    code: "MHM",
    logo: "",
    domains: [
      "@mahindramotors.com",
      "@mahindratech.com",
      "@mahindravehicles.com",
      "@marvel.com",
      "@dccomics.com",
    ],
    reg_date: "June 2021",
    user: [
      {
        user_id: 1,
        user_name: "Salma Shaik",
        email: "salma.rivaan@gmail.com",
      },
      {
        user_id: 2,
        user_name: "Afsar",
        email: "afsarsk@gmail.com",
      },
      {
        user_id: 3,
        user_name: "Arwaan",
        email: "arwaanafsar@gmail.com",
      },
      {
        user_id: 4,
        user_name: "Nidhi",
        email: "nidhiayyar@gmail.com",
      },
      {
        user_id: 5,
        user_name: "Jitesh Nair",
        email: "Jiteshnair@gmail.com",
      },
      {
        user_id: 6,
        user_name: "Swati",
        email: "swatik@gmail.com",
      },
    ],
    entities: [
      {
        entity_id: 1,
        billing_location: "Riyadh,Kingdom of Saudi Arabia",
        entity_name: "Lucas Films Private Limited",
        entity_code: "LUCF01",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>LucasFilms MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 June 2025",
        duration_of_storage: "90 days",
        TAX_reg_number: "JHGJH89KU0873KHH",
        TRN_validity: "5 June 2025",
        currency: "US Dollar (S)",
        vat: "5%",
        wht: "5%",
        corporate_price_per_MSLA: [
          {
            service: "Arabic Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 2,
        billing_location: "Banglaore,India",
        entity_name: "Einfochip Private Limited",
        entity_code: "EINFO21",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>EINFO MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "2 March 2025",
        duration_of_storage: "60 days",
        TAX_reg_number: "KHGJH89KU0873KHH",
        TRN_validity: "5 June 2026",
        currency: "US Dollar (S)",
        vat: "7%",
        wht: "8%",
        corporate_price_per_MSLA: [
          {
            service: "Sanskrit Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.2,
            Offered_price: 0.19,
            discount: "10% ( 19% )",
          },
        ],
      },
      {
        entity_id: 3,
        billing_location: "Tesla,United States Of America",
        entity_name: "Tesla Motors Private Limited",
        entity_code: "TSL01",
        MSLA_valid: "3 June 2022 - 5 June 2030",
        file_sharing: "External",
        address: ["Line1", "Line2", "City", "Country", "ZIP Code"],
        charge_code: "Required",
        MSLA: "321412 EZ<>Tesla MOU_signed by George.pdf",
        company_reg_number: "UICE8F2T749WEY",
        company_reg_validity: "25 January 2023",
        duration_of_storage: "100 days",
        TAX_reg_number: "JHGJHKJDFH873K2H",
        TRN_validity: "5 June 2025",
        currency: "US Dollar (S)",
        vat: "5%",
        wht: "5%",
        corporate_price_per_MSLA: [
          {
            service: "Latin Language Translation",
            EZ_assured: true,
            units: "Words",
            list_price: 0.1,
            Offered_price: 0.09,
            discount: "8% ( 10% )",
          },
        ],
      },
    ],
  },
];
